[workspace]
members = [
    "src/apps/bench/rustbenchs",
    "src/apps/disktest",
    "src/apps/rusthello",
    "src/apps/rustunittests",
    "src/libs/rust/base",
    "src/libs/rust/isr",
    "src/libs/rust/m3",
    "src/libs/rust/paging",
    "src/libs/rust/pci",
    "src/libs/rust/resmng",
    "src/libs/rust/thread",
    "src/pemux",
    "src/rustkernel",
    "src/server/disk",
    "src/server/pager",
    "src/server/pipes",
    "src/server/root",
    "src/server/vterm",
]

[profile.release]
lto = true
panic = 'abort'

[profile.dev]
panic = 'abort'
