[workspace]
members = [
    "src/apps/bench/rustbenchs",
    "src/apps/pemux",
    "src/apps/rusthello",
    "src/apps/rustunittests",
    "src/libs/rustbase",
    "src/libs/rustm3",
    "src/libs/rustresmng",
    "src/libs/rustthread",
    "src/server/pipes",
    "src/server/root",
    "src/server/subsys",
    "src/server/vterm",
]

[profile.release]
lto = true
panic = 'abort'

[profile.dev]
panic = 'abort'
