[package]
name = "disk"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/disk.rs"
crate-type = ["staticlib"]

[dependencies]
bitflags = "2.1.0"
m3 = { path = "../../libs/rust/m3" }
num_enum = { version = "0.6.1", default-features = false }
pci = { path = "../../libs/rust/pci" }
