[package]
name = "pemux"
version = "0.1.0"

[lib]
path = "src/pemux.rs"
crate-type = ["staticlib"]

[dependencies]
cfg-if = "*"
base = { path = "../libs/rust/base" }
paging = { path = "../libs/rust/paging" }
