[package]
name = "acceltest"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/acceltest.rs"
crate-type = ["staticlib"]

[dependencies]
m3 = { path = "../../libs/rust/m3" }
accel = { path = "../../libs/rust/accel" }
