dirs = [
    'allocator',
    'bench',
    'bsdutils',
    'coreutils',
    'cppnettests',
    'cpprdfile',
    'cpppipe',
    'disktest',
    'dosattack',
    'evilcompute',
    'faulter',
    'filterchain',
    'hashmuxtests',
    'hello',
    'info',
    'libctest',
    'msgchan',
    'netechoserver',
    'noop',
    'parchksum',
    'ping',
    'pipeline',
    'queue',
    'rdfile',
    'resmngtest',
    'rusthello',
    'rustnettests',
    'ruststandalone',
    'ruststdtest',
    'rustunittests',
    'shell',
    'spammer',
    'standalone',
    'timertest',
    'unittests',
]

def build(gen, env):
    for d in dirs:
        env.sub_build(gen, d)
