[build]
rustflags = ["-Wrust-2018-idioms"]
target = "toolchain/rust/riscv64-linux-m3-musl.json"

[target.'riscv64-linux-m3-muslcov']
rustflags = ["-Cinstrument-coverage", "-Zno-profiler-runtime"]
[target.'x86_64-linux-m3-muslcov']
rustflags = ["-Cinstrument-coverage", "-Zno-profiler-runtime"]
