[package]
name = "subsys"
version = "0.1.0"

[lib]
path = "src/subsys.rs"
crate-type = ["staticlib"]

[dependencies]
m3 = { path = "../../libs/rust/m3" }
resmng = { path = "../../libs/rust/resmng" }
thread = { path = "../../libs/rust/thread" }
