[package]
name = "subsys"
version = "0.1.0"

[lib]
path = "src/subsys.rs"
crate-type = ["staticlib"]

[dependencies]
m3 = { path = "../../libs/rustm3" }
resmng = { path = "../../libs/rustresmng" }
thread = { path = "../../libs/rustthread" }
