[package]
name = "hashmuxtests"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/hashmuxtests.rs"
crate-type = ["staticlib"]

[dependencies]
m3 = { path = "../../libs/rust/m3" }
hex-literal = "0.3.4"
