[package]
name = "peidle"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/peidle.rs"
crate-type = ["staticlib"]

[dependencies]
base = { path = "../libs/rust/base" }
isr = { path = "../libs/rust/isr" }
