[workspace]
members = [
    "apps/bench/rustbenchs",
    "apps/rusthello",
    "apps/rustunittests",
    "apps/rust/clisrv/client",
    "apps/rust/clisrv/server",
    "apps/rust/kernel",
    "apps/rust/test",
    "libs/rustbase",
    "libs/rustm3",
    "libs/rustthread",
    "server/root",
]

[profile.release]
lto = true
panic = 'abort'

[profile.dev]
panic = 'abort'
