[package]
name = "rusttest"
version = "0.1.0"

[lib]
name = "rusttest"
crate-type = ["staticlib"]

[profile.release]
lto = true
panic = 'abort'

[profile.dev]
panic = 'abort'

[dependencies]
m3 = { path = "../../libs/rust" }
